---

# port: 4000
# host: 0.0.0.0
# safe: false


### site serving configuration ###
exclude: [CNAME, README.md, .gitignore]
permalink: /:title ## disables post output
timezone: null
lsi: false
markdown: kramdown


### content configuration ###
title:       "SAP Document Stream"
keywords:    "SAP, Document Management, PDF Conversion, Automated Workflow, Batch Processing, Digital Signatures, PDF Stamping, PDF Dossiers, GDPR Compliance, Data Security, Cyber-Security, ERP, S/4HANA, Swiss Engineering, Cost Savings, Operational Efficiency, OAuth2 Authentication"
description: "Unlock unprecedented efficiency in SAP document management with SAP Document Stream. Automated workflows, PDF conversions, GDPR compliance, and advanced security features in one seamless solution."
source_link: "https://www.znk.lu/"
favicon:     "img/favicon.ico"
touch_icon:  "img/apple-touch-icon.png"
google_analytics_key: UA-49607422-1 ## put YOUR key here to enable tracking! (blank to disable)


### template colors, used site-wide via css ###
colors:
  black:     '#111111'
  white:     '#f8f8f8'
  blue:      '#49a7e9'
  green:     '#9bcf2f'
  purple:    '#c869bf'
  orange:    '#fab125'
  turquoise: '#0fbfcf'

kramdown:
  auto_ids:  false

url: "https://harryf.github.io/znkpdftools/"
plugins:
  - jekyll-sitemap

